In [114]:
import numpy as np

In [115]:
l=[1,2,3]
a=np.array(l, dtype=float)
print(l)
print(a)

[1, 2, 3]
[1. 2. 3.]


In [116]:
l3=np.asarray(l2)
print(l3)
print(type(l3))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
<class 'numpy.ndarray'>


In [117]:
l4=np.zeros((2,3))
l5=[34,45,5,"f",5,l2,l4]
a4=np.asarray(l5)
print(a5)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (7,) + inhomogeneous part.

In [ ]:

l6=[45,2,56,7,86,87,500,700,255,3,256]
a6=np.asarray(l6,dtype=np.int16)
print(a6)
print(l6)

[ 45   2  56   7  86  87 500 700 255   3 256]
[45, 2, 56, 7, 86, 87, 500, 700, 255, 3, 256]


In [ ]:
l7=[45,2,3]
a7=np.asarray(l7,dtype=np.uint32)
print(a7)
print(l7)

[45  2  3]
[45, 2, 3]


In [ ]:
l8=[-45,2,3]
a8=np.asarray(l8,dtype=np.int32)
print(a8)
print(l8)

[-45   2   3]
[-45, 2, 3]


In [ ]:
a9=np.arange(20)
print(a9)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [ ]:
a10=np.linspace(1,10,5)
print(a10)

[ 1.    3.25  5.5   7.75 10.  ]


In [ ]:
a11=np.arange(1,10,2)
print(a11)

[1 3 5 7 9]


In [ ]:
l11=[-45,2,3]
a11=np.asarray(l11,dtype=float)
print(a11)
print(l11)

[-45.   2.   3.]
[-45, 2, 3]


In [ ]:
# l12=[45,2,3]
a12=np.arange(2,10,2,dtype=float)
print(a12)

[2. 4. 6. 8.]


In [ ]:
a13=np.zeros((3,2))
print(l3)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
l15=np.array([3,2,3,45,5,6,77,8,4,3,5,6])
a15=l15[:6]
print(a15)
a15=a15+1
print(a15)

[ 3  2  3 45  5  6]
[ 4  3  4 46  6  7]


In [30]:
import numpy as np
mylist=[12,45,10,300,125,8,5]
nplist=np.array(mylist,dtype=np.uint32)
print(nplist)
newlist=np.arange(10,50,5)
print(newlist)
zlist=np.zeros((3,3))
print(zlist)
flist=np.array(mylist,dtype='float')
print(flist)

addlist=nplist[:5]
print(nplist)
addlist=addlist+5
print(addlist)

nplist=np.multiply(nplist,3)
print(nplist)
zlist=np.multiply(zlist,3)
print(zlist)

clist=np.copy(nplist)
clist[-1]=999
# chlist=clist[num]=999
print(clist)

# print(chlist)


[ 12  45  10 300 125   8   5]
[10 15 20 25 30 35 40 45]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[ 12.  45.  10. 300. 125.   8.   5.]
[ 12  45  10 300 125   8   5]
[ 17  50  15 305 130]
[ 36 135  30 900 375  24  15]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[ 36 135  30 900 375  24 999]
